#!/bin/bash
# Updates a database by running patches
PATH=/bin:/usr/bin:$HOME/bin:${0%/*}

source db-library.sh
source db-load-settings.sh;
source db-get-password.sh;

load_history
awk -f $DB_UTILS_ROOT/db-get-installed-tables.awk <$PATCH_HISTORY |
xargs mysqldump $db -u "$user" -p"$PASSWORD" --skip-dump-date --no-data;
