#!/bin/bash
# Updates a database by running patches
PATH=/bin:/usr/bin:$HOME/bin:${0%/*}

source db-library.sh
source db-load-settings.sh;
source db-get-password.sh;

get_history | awk -f db-get-installed-tables.awk | \
xargs mysqldump $db -u "$user" -p"$PASSWORD" --skip-dump-date --no-data;
