#!/bin/bash
# Deletes all installed tables from the specified database.
PATH=/bin:/usr/bin:$HOME/bin:${0%/*}

source db-library.sh;
source db-load-settings.sh
source db-get-password.sh;

if ! get_tables | egrep -x 'patches' >/dev/null; then
    echo "db: nothing to erase in $db" 1>&2
    exit 0;
fi

history=/tmp/db-erase-$db-history.$$
staged=/tmp/db-erase-$db-staged.$$
last_error=/tmp/db-erase-$db-error.$$

function cleanup {
    rm -f $staged $tables $last_error $history
}
trap cleanup EXIT
trap 'echo; cleanup; exit 1' INT TERM

get_history | awk -f db-get-installed-tables.awk | source db-filter-tables.sh >$staged
if [ ! -s $staged ]; then
    echo "db: nothing to erase in $db" 1>&2
    exit 0;
fi;

if [ ! $FORCE ]; then
    echo "Installed tables in $db:"
    cat $staged
    read -p"Destroy listed tables in $db? (y/n): " r
    case $r in
        y*) ;;
        *) exit 1
    esac
fi

tries=0
errors=0
while [ $tries -lt 20 ]; do
    log "Starting erase, attempt $tries"
    for table in `cat $staged`; do
        log "Attempting to drop '$table'"
        sql_raw "drop view if exists $table; drop table if exists $table;" 2>$last_error
        if [ -s $last_error ]; then
            let errors++;
            warn "error during removal: $(cat $last_error)"
        fi
    done
    if [ $errors = 0 ]; then
        break
    else
        warn "removal failed with $errors error(s)"
        errors=0
    fi
    let tries++
done

[ $errors -lt 1 ] || error "remove failed after 20 tries"

sql "truncate patches; truncate patch_changelog"

if [ $(get_tables | source db-filter-tables.sh | wc -l) -gt 0 ]; then 
    echo 'The following untracked tables were not removed:'
    get_tables | source db-filter-tables.sh;
fi;
