#!/bin/sh
# Initializes a directory to be used as a db-utils repository
PATH=/bin:/usr/bin:$HOME/bin:${0%/*}

DB_DONT_COMPLAIN=0 . db-load-settings.sh #2>/dev/null

CONFIG_ROOT='./.db'

if [ -z "$db" ]; then
    echo "db: Usage db-init [options] <database-name>" 1>&2
    exit 1
fi

if [ ! -e $CONFIG_ROOT/$db ]; then
    if ! mkdir -p $CONFIG_ROOT/$db; then
        exit 1
    fi
    if [ ! -e $CONFIG_ROOT/.gitignore ]; then
        cat >$CONFIG_ROOT/.gitignore <<X
*password
*.log
X
    fi
fi

if [ ! -s $CONFIG_ROOT/default ]; then
    echo $db >$CONFIG_ROOT/default
fi
touch $CONFIG_ROOT/default

SETTINGS="$CONFIG_ROOT/$db/settings"
if [ ! -s "$SETTINGS" ]; then
    if [ -n "$root" ]; then
        echo "root=$root" >>$SETTINGS
    fi
fi;
touch $CONFIG_ROOT/settings

if [ -n "$PASSWORD" ]; then
    echo $PASSWORD >$CONFIG_ROOT/$db/password
fi
touch $CONFIG_ROOT/$db/password
touch $CONFIG_ROOT/password

if [ ! -e "$root" ]; then
    if ! mkdir $root; then
        exit 1;
    fi
fi

if [ ! -e $patchlist ]; then
    echo "# List your patches for $db here, relative to '$root'" >$patchlist
fi
if ! touch $patchlist; then
    exit 1;
fi

touch $CONFIG_ROOT/init.sql
touch $CONFIG_ROOT/$db/init.sql

touch $CONFIG_ROOT/ignore
touch $CONFIG_ROOT/$db/ignore
