#!/bin/sh
# Initializes a directory to be used as a db-utils repository
PATH=/bin:/usr/bin:$HOME/bin:${0%/*}

DB_DONT_COMPLAIN=0 DB_EXPLICIT_ONLY=0 . db-load-settings.sh #2>/dev/null

CONFIG_ROOT='./.db'

if [ -z "$db" ]; then
    echo "db: Usage db-init [options] <database-name>" 1>&2
    exit 1
fi

DB_CONFIG_ROOT=$CONFIG_ROOT/$db

if [ ! -e $DB_CONFIG_ROOT ]; then
    if ! mkdir -p $DB_CONFIG_ROOT; then
        exit 1
    fi
fi

if [ ! -e $CONFIG_ROOT/.gitignore ]; then
    cat >$CONFIG_ROOT/.gitignore <<X
*password
*log
*database
X
fi

if [ ! -s $CONFIG_ROOT/default ]; then
    echo $db >$CONFIG_ROOT/default
fi
touch $CONFIG_ROOT/default

SETTINGS="$DB_CONFIG_ROOT/settings"
if [ ! -s "$SETTINGS" ]; then
    if [ -n "$root" ] && [ "$root" != '.' ]; then
        echo "root=$root" >>$SETTINGS
    fi
fi;
touch $CONFIG_ROOT/settings

if [ -n "$PASSWORD" ]; then
    echo $PASSWORD >$DB_CONFIG_ROOT/password
fi
touch $DB_CONFIG_ROOT/password
touch $CONFIG_ROOT/password

if [ ! -e "$root" ]; then
    if ! mkdir $root; then
        exit 1;
    fi
fi

if [ ! -e $patchlist ]; then
    echo "# List your patches for $db here, relative to '$root'" >$patchlist
fi
if ! touch $patchlist; then
    exit 1;
fi

touch $DB_CONFIG_ROOT/database

touch $CONFIG_ROOT/init.sql
touch $DB_CONFIG_ROOT/init.sql

touch $CONFIG_ROOT/ignore
touch $DB_CONFIG_ROOT/ignore
